spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

groq.api.keys=${GROQ_API_KEYS}
azure.storage.connection-string=${AZURE_STORAGE_CONNECTION_STRING}
azure.storage.container-name=${AZURE_STORAGE_CONTAINER_NAME}

jwt.secret=${JWT_SECRET_KEY}

app.superadmin1.email=${SUPERADMIN1_EMAIL}
app.superadmin1.password=${SUPERADMIN1_PASSWORD}
app.superadmin2.email=${SUPERADMIN2_EMAIL}
app.superadmin2.password=${SUPERADMIN2_PASSWORD}